# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Run Hourly Cache

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Set up Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Python dependencies
      working-directory: src
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: Intall Node dependencies
      working-directory: src
      run: yarn

    - name: Clone previous cache data
      run: |
        git clone https://github.com/open-covid-19/data --single-branch -b cache ./output/cache

    - name: Cache data sources
      working-directory: src
      run: |
        python ./cache.py --continue-on-error

    - name: Deploy data to server
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: cache
        publish_dir: ./output/cache
